// <auto-generated />
using System;
using Kairos.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kairos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250606183602_CREATEMIGRATIONS")]
    partial class CREATEMIGRATIONS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kairos.Domain.Entities.EventoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagemUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("StatusAprovacao")
                        .HasColumnType("int");

                    b.Property<int>("TipoEventoID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoEventoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Tbl_Evento", (string)null);
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PerfilEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Organizador"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Membro"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PresencaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHoraCheckin")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Tbl_Presenca", (string)null);
                });

            modelBuilder.Entity("Kairos.Domain.Entities.SugestaoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventoID")
                        .HasColumnType("int");

                    b.Property<int>("StatusSugestao")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Tbl_Sugestao", (string)null);
                });

            modelBuilder.Entity("Kairos.Domain.Entities.TipoEventoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Tbl_TipoEvento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Culto"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vigília"
                        });
                });

            modelBuilder.Entity("Kairos.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PerfilID")
                        .HasColumnType("int");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("BI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilID");

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("Tbl_Usuario", (string)null);
                });

            modelBuilder.Entity("Kairos.Domain.Entities.EventoEntity", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.TipoEventoEntity", "TipoEvento")
                        .WithMany("Eventos")
                        .HasForeignKey("TipoEventoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TipoEvento_Eventos");

                    b.HasOne("Kairos.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Eventos")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Eventos");

                    b.Navigation("TipoEvento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PresencaEntity", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.EventoEntity", "Evento")
                        .WithMany("Presencas")
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Evento_Presenca");

                    b.HasOne("Kairos.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Presencas")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Presenca");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.SugestaoEntity", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.EventoEntity", "Evento")
                        .WithMany("Sugestoes")
                        .HasForeignKey("EventoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Evento_Sugestao");

                    b.HasOne("Kairos.Domain.Entities.UsuarioEntity", "Usuario")
                        .WithMany("Sugestoes")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Sugestao");

                    b.Navigation("Evento");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.UsuarioEntity", b =>
                {
                    b.HasOne("Kairos.Domain.Entities.PerfilEntity", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Perfil_Usuario");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.EventoEntity", b =>
                {
                    b.Navigation("Presencas");

                    b.Navigation("Sugestoes");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.PerfilEntity", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.TipoEventoEntity", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("Kairos.Domain.Entities.UsuarioEntity", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Presencas");

                    b.Navigation("Sugestoes");
                });
#pragma warning restore 612, 618
        }
    }
}
