global using System.Text.Json.Serialization;
global using Kairos.Domain.Abstrations.Shared;
global using Kairos.Domain.Abstrations.Base;
global using Kairos.Domain.Abstrations.Enums;
global using Kairos.Domain.Abstrations.Exceptions;
global using Kairos.Domain.Entities;
global using System.Linq.Expressions;
global using Kairos.Domain.Abstrations.Pagination;
global using System.Text.RegularExpressions;